#!/bin/sh
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start firewall at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

DAEMON_LOG=/var/log/firewall.log

case "$1" in
  start)
    echo -n "$0 : "
		sh /etc/init.d/firewall.disable
        sh /etc/init.d/firewall.enable
    echo "[Started]"
    ;;
  stop)
    echo -n "$0 : "
    sh /etc/init.d/firewall.disable
    echo "[Stopped]"
    ;;
  *)
    echo "Usage: $0 {start stop}"
    ;;
esac

exit 0
